"""
Gmail API Integration — OAuth2 + Send
=======================================
Allows users to connect their Gmail account and send cold outreach
emails generated by the Cold Email Generator (P6.2) directly from
the AI Job Apply platform.

OAuth2 Flow:
  1. User visits /api/outreach/gmail/auth-url  → redirected to Google consent
  2. Google redirects to /api/outreach/gmail/callback with ?code=...
  3. Exchange code for access + refresh tokens
  4. Store tokens (returned to client; client stores in Supabase)

Endpoints:
  GET  /api/outreach/gmail/auth-url         → Google consent page URL
  GET  /api/outreach/gmail/callback         → OAuth2 callback (exchange code)
  POST /api/outreach/gmail/send             → send a single email
  POST /api/outreach/gmail/send-batch       → send multiple emails (rate-limited)
  GET  /api/outreach/gmail/profile          → authenticated user's Gmail address
"""

import os
import base64
import json
import asyncio
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from typing import Optional, List

from fastapi import APIRouter, HTTPException, Query, Depends
from auth import get_current_user
from fastapi.responses import RedirectResponse
from pydantic import BaseModel

from google.oauth2.credentials import Credentials
from google.auth.transport.requests import Request as GoogleRequest
from google_auth_oauthlib.flow import Flow
from googleapiclient.discovery import build
from googleapiclient.errors import HttpError

router = APIRouter()

# ── Config ────────────────────────────────────────────────────────────

GOOGLE_CLIENT_ID     = os.getenv("GOOGLE_CLIENT_ID", "")
GOOGLE_CLIENT_SECRET = os.getenv("GOOGLE_CLIENT_SECRET", "")
GMAIL_REDIRECT_URI   = os.getenv("GMAIL_REDIRECT_URI", "http://localhost:8000/api/outreach/gmail/callback")

GMAIL_SCOPES = [
    "https://www.googleapis.com/auth/gmail.send",
    "https://www.googleapis.com/auth/gmail.readonly",
    "openid",
    "email",
    "profile",
]

OAUTH_CLIENT_CONFIG = {
    "web": {
        "client_id": GOOGLE_CLIENT_ID,
        "client_secret": GOOGLE_CLIENT_SECRET,
        "auth_uri": "https://accounts.google.com/o/oauth2/auth",
        "token_uri": "https://oauth2.googleapis.com/token",
        "redirect_uris": [GMAIL_REDIRECT_URI],
    }
}


# ── Models ────────────────────────────────────────────────────────────

class GmailTokens(BaseModel):
    """Credentials to be stored by the client (Supabase) and passed back on each request."""
    access_token: str
    refresh_token: Optional[str] = None
    token_uri: str = "https://oauth2.googleapis.com/token"
    client_id: str = ""
    client_secret: str = ""
    scopes: Optional[List[str]] = None
    expiry: Optional[str] = None    # ISO datetime string

class SendEmailRequest(BaseModel):
    tokens: GmailTokens
    to: str                          # recipient email address
    subject: str
    body_html: str
    body_plain: Optional[str] = None
    reply_to: Optional[str] = None
    cc: Optional[List[str]] = None

class SendEmailResponse(BaseModel):
    status: str
    message_id: Optional[str] = None
    thread_id: Optional[str] = None
    to: str
    subject: str

class BatchSendRequest(BaseModel):
    tokens: GmailTokens
    emails: List[SendEmailRequest]
    delay_seconds: float = 2.0       # Rate-limit: pause between sends (keep < 1 send/sec to avoid spam flags)

class BatchSendResponse(BaseModel):
    status: str
    sent: List[SendEmailResponse]
    failed: List[str]                # list of recipient emails that failed
    total_sent: int
    total_failed: int

class GmailProfile(BaseModel):
    email_address: str
    messages_total: Optional[int] = None
    threads_total: Optional[int] = None

class AuthUrlResponse(BaseModel):
    auth_url: str
    state: str

class TokenExchangeResponse(BaseModel):
    status: str
    tokens: GmailTokens
    gmail_address: str


# ── Helpers ───────────────────────────────────────────────────────────

def _build_credentials(tokens: GmailTokens) -> Credentials:
    """Reconstruct a Google Credentials object from stored tokens."""
    from datetime import datetime
    expiry = None
    if tokens.expiry:
        try:
            expiry = datetime.fromisoformat(tokens.expiry)
        except ValueError:
            pass

    creds = Credentials(
        token=tokens.access_token,
        refresh_token=tokens.refresh_token,
        token_uri=tokens.token_uri,
        client_id=tokens.client_id or GOOGLE_CLIENT_ID,
        client_secret=tokens.client_secret or GOOGLE_CLIENT_SECRET,
        scopes=tokens.scopes or GMAIL_SCOPES,
    )
    if expiry:
        creds.expiry = expiry
    return creds


def _refresh_if_needed(creds: Credentials) -> Credentials:
    """Refresh the access token if it has expired."""
    if creds.expired and creds.refresh_token:
        creds.refresh(GoogleRequest())
    return creds


def _build_message(
    sender: str,
    to: str,
    subject: str,
    body_html: str,
    body_plain: Optional[str],
    reply_to: Optional[str],
    cc: Optional[List[str]],
) -> dict:
    """Build a base64url-encoded raw email message for the Gmail API."""
    msg = MIMEMultipart("alternative")
    msg["From"] = sender
    msg["To"] = to
    msg["Subject"] = subject
    if reply_to:
        msg["Reply-To"] = reply_to
    if cc:
        msg["Cc"] = ", ".join(cc)

    if body_plain:
        msg.attach(MIMEText(body_plain, "plain"))
    msg.attach(MIMEText(body_html, "html"))

    raw = base64.urlsafe_b64encode(msg.as_bytes()).decode()
    return {"raw": raw}


def _tokens_to_response(creds: Credentials) -> GmailTokens:
    """Convert refreshed Credentials back to our GmailTokens model."""
    expiry_str = creds.expiry.isoformat() if creds.expiry else None
    return GmailTokens(
        access_token=creds.token,
        refresh_token=creds.refresh_token,
        token_uri=creds.token_uri,
        client_id=creds.client_id,
        client_secret=creds.client_secret,
        scopes=list(creds.scopes) if creds.scopes else None,
        expiry=expiry_str,
    )


def _check_credentials_configured() -> None:
    """Raise a clear error if Google OAuth credentials aren't set up."""
    if not GOOGLE_CLIENT_ID or not GOOGLE_CLIENT_SECRET:
        raise HTTPException(
            status_code=503,
            detail=(
                "Google OAuth credentials not configured. "
                "Set GOOGLE_CLIENT_ID and GOOGLE_CLIENT_SECRET in your .env file. "
                "Get them from https://console.cloud.google.com/apis/credentials"
            ),
        )


# ── Endpoints ─────────────────────────────────────────────────────────

@router.get("/outreach/gmail/auth-url", response_model=AuthUrlResponse)
async def get_gmail_auth_url(
    redirect_uri: Optional[str] = Query(default=None, description="Custom redirect URI for the frontend callback")
):
    """
    Step 1 of Gmail OAuth2 — returns the Google consent page URL.
    Redirect the user to this URL. After consent, Google redirects
    back to the callback endpoint with ?code=... and ?state=...
    """
    _check_credentials_configured()

    config = OAUTH_CLIENT_CONFIG.copy()
    actual_redirect = redirect_uri or GMAIL_REDIRECT_URI
    config["web"]["redirect_uris"] = [actual_redirect]

    flow = Flow.from_client_config(config, scopes=GMAIL_SCOPES)
    flow.redirect_uri = actual_redirect

    auth_url, state = flow.authorization_url(
        access_type="offline",    # request refresh token
        include_granted_scopes="true",
        prompt="consent",         # force consent so we always get refresh_token
    )

    return AuthUrlResponse(auth_url=auth_url, state=state)


@router.get("/outreach/gmail/callback", response_model=TokenExchangeResponse)
async def gmail_oauth_callback(
    code: str = Query(..., description="Authorization code from Google"),
    state: Optional[str] = Query(default=None),
    redirect_uri: Optional[str] = Query(default=None),
):
    """
    Step 2 of Gmail OAuth2 — exchange the authorization code for tokens.
    Call this endpoint with the ?code= parameter Google sends after consent.
    Returns tokens that the frontend should store in Supabase for the user.
    """
    _check_credentials_configured()

    actual_redirect = redirect_uri or GMAIL_REDIRECT_URI
    config = OAUTH_CLIENT_CONFIG.copy()
    config["web"]["redirect_uris"] = [actual_redirect]

    try:
        flow = Flow.from_client_config(config, scopes=GMAIL_SCOPES, state=state)
        flow.redirect_uri = actual_redirect
        flow.fetch_token(code=code)
        creds = flow.credentials
    except Exception as exc:
        raise HTTPException(status_code=400, detail=f"OAuth token exchange failed: {str(exc)}")

    # Get the user's Gmail address
    try:
        service = build("gmail", "v1", credentials=creds)
        profile = service.users().getProfile(userId="me").execute()
        gmail_address = profile.get("emailAddress", "")
    except Exception:
        gmail_address = ""

    tokens = _tokens_to_response(creds)

    return TokenExchangeResponse(
        status="success",
        tokens=tokens,
        gmail_address=gmail_address,
    )


@router.get("/outreach/gmail/profile", response_model=GmailProfile)
async def get_gmail_profile(
    access_token: str = Query(..., description="Gmail access token"),
    refresh_token: Optional[str] = Query(default=None),
    user: dict = Depends(get_current_user),
):
    """
    Returns the authenticated user's Gmail address and mailbox stats.
    Use this to verify the connection is working after OAuth.
    """
    tokens = GmailTokens(access_token=access_token, refresh_token=refresh_token)
    try:
        creds = _build_credentials(tokens)
        creds = _refresh_if_needed(creds)
        service = build("gmail", "v1", credentials=creds)
        profile = service.users().getProfile(userId="me").execute()
        return GmailProfile(
            email_address=profile.get("emailAddress", ""),
            messages_total=profile.get("messagesTotal"),
            threads_total=profile.get("threadsTotal"),
        )
    except HttpError as exc:
        raise HTTPException(status_code=exc.status_code, detail=str(exc))
    except Exception as exc:
        raise HTTPException(status_code=500, detail=f"Failed to get profile: {str(exc)}")


@router.post("/outreach/gmail/send", response_model=SendEmailResponse)
async def send_gmail(body: SendEmailRequest, user: dict = Depends(get_current_user)):
    """
    Send a single outreach email via the authenticated user's Gmail account.
    
    Accepts the GmailTokens from the OAuth callback and the email content
    generated by /api/outreach/generate-email (P6.2). Returns the
    Gmail message_id for tracking.
    
    Note: refreshed tokens are returned in the response if the token was expired.
    """
    try:
        creds = _build_credentials(body.tokens)
        creds = _refresh_if_needed(creds)
        service = build("gmail", "v1", credentials=creds)

        # Get sender's email address
        profile = service.users().getProfile(userId="me").execute()
        sender_email = profile.get("emailAddress", "me")

        message = _build_message(
            sender=sender_email,
            to=body.to,
            subject=body.subject,
            body_html=body.body_html,
            body_plain=body.body_plain,
            reply_to=body.reply_to,
            cc=body.cc,
        )

        sent = service.users().messages().send(userId="me", body=message).execute()

        return SendEmailResponse(
            status="sent",
            message_id=sent.get("id"),
            thread_id=sent.get("threadId"),
            to=body.to,
            subject=body.subject,
        )

    except HttpError as exc:
        raise HTTPException(
            status_code=exc.status_code,
            detail=f"Gmail API error: {exc.reason}",
        )
    except Exception as exc:
        raise HTTPException(status_code=500, detail=f"Send failed: {str(exc)}")


@router.post("/outreach/gmail/send-batch", response_model=BatchSendResponse)
async def send_batch_gmail(body: BatchSendRequest, user: dict = Depends(get_current_user)):
    """
    Send multiple outreach emails sequentially with a configurable delay
    between each one to avoid triggering Gmail's spam filters.
    
    Recommended delay: 2-5 seconds between sends.
    Maximum batch size: 50 emails.
    
    Pair with /api/outreach/generate-email/batch (P6.2) to find contacts,
    generate personalized emails, and send them all in one workflow.
    """
    if len(body.emails) > 50:
        raise HTTPException(
            status_code=400,
            detail="Maximum 50 emails per batch. Gmail daily send limit is 500."
        )

    try:
        creds = _build_credentials(body.tokens)
        creds = _refresh_if_needed(creds)
        service = build("gmail", "v1", credentials=creds)
        profile = service.users().getProfile(userId="me").execute()
        sender_email = profile.get("emailAddress", "me")
    except Exception as exc:
        raise HTTPException(status_code=401, detail=f"Authentication failed: {str(exc)}")

    sent_results: List[SendEmailResponse] = []
    failed_recipients: List[str] = []

    for email in body.emails:
        try:
            message = _build_message(
                sender=sender_email,
                to=email.to,
                subject=email.subject,
                body_html=email.body_html,
                body_plain=email.body_plain,
                reply_to=email.reply_to,
                cc=email.cc,
            )
            result = service.users().messages().send(userId="me", body=message).execute()
            sent_results.append(SendEmailResponse(
                status="sent",
                message_id=result.get("id"),
                thread_id=result.get("threadId"),
                to=email.to,
                subject=email.subject,
            ))
        except Exception as exc:
            failed_recipients.append(f"{email.to}: {str(exc)}")

        # Rate-limit delay — avoids Gmail spam flag
        if body.delay_seconds > 0:
            await asyncio.sleep(body.delay_seconds)

    return BatchSendResponse(
        status="completed",
        sent=sent_results,
        failed=failed_recipients,
        total_sent=len(sent_results),
        total_failed=len(failed_recipients),
    )
